# Generated by Django 5.1.3 on 2025-04-23 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prescription_file',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receipt_sent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_email',
        ),
    ]
