# Generated by Django 4.2.18 on 2025-02-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_total_price_order_payment_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Khalti', 'Khalti'), ('Cash on Delivery', 'Cash on Delivery')], max_length=20, null=True),
        ),
    ]
