# Generated by Django 5.1.3 on 2025-04-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_appointment_veterinarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_poisonous',
            field=models.BooleanField(default=False, help_text='Indicates if the medicine is potentially poisonous to animals'),
        ),
    ]
